#index:
#    path: /
#    controller: App\Controller\DefaultController::index

register:
    path: /register
    controller: App\Controller\MainController::register
    methods: POST

login_check:
    path: /login_check
    methods:  [POST]

api:
    path: /api
    controller: App\Controller\DefaultController::api

